### ISSUE TITLE
我在linux上面部署出现问题

### ISSUE THREAD

**Issue by Sn0rt** [meiu/meiupic#1]
Warning: file_put_contents(/var/www/html/data/cache/8/b3/8b31da0b38fcc7ef81d9c6b0b7104984.php): failed to open stream: No such file or directory in /var/www/html/core/driver/cache/file.php on line 53

**Comment by liqimore** [comment]
目录权限你是怎么设置的呢？ 很可能是权限不足 给他写入试试

**Comment by Sn0rt** [comment]
谢了 已经搞定了.
