### ISSUE TITLE
新版本如何配置？

### ISSUE THREAD

**Issue by stardock** [meiu/meiupic#3]
部署之后访问出现如下错误：
[DB] 连接至数据库服务器失败：(127.0.0.1,root)！
网站也不出现配置向导， 应该是需要修改预配置信息。。。
那我应该修改哪个配置文件， 不太懂。。。

**Comment by meiu** [comment]
新版开发中！目前还处于不可用状态。
等达到基本可用状态时，我会写一个安装说明的。

**Comment by stardock** [comment]
感谢您的开发，期待中
