### ISSUE TITLE
老用户的心声

### ISSUE THREAD

**Issue by LuRenJiasWorld** [meiu/meiupic#4]
用了很多年meiupic，正准备进行二次开发，发现作者开了新坑，开心:-D，现在自己也有了一定的开发能力，如果不嫌弃的话，希望能够帮上忙~

**Comment by lepig** [comment]
这个系统确实很不错。风格简洁，没有太多的花哨。希望可以帮上忙。

**Comment by meiu** [comment]
新版已经勉强可以用了，可以下载尝个鲜吧。
