### ISSUE TITLE
虚拟主机，无法创建缓存文件

### ISSUE THREAD

**Issue by lepig** [meiu/meiupic#7]
`
Warning: file_put_contents(/home/host2073/domains/img.hashx.cn/public_html/data/cache/8/b3/8b31da0b38fcc7ef81d9c6b0b7104984.php) [function.file-put-contents]: failed to open stream: No such file or directory in /home/host2073/domains/img.hashx.cn/public_html/core/driver/cache/file.php on line 53
`

按照ReadMe里面配置完以后，上传到空间以后出现这样的问题。我登录虚拟主机后台发现并没有生成`data/cache/8/b3/8b31da0b38fcc7ef81d9c6b0b7104984.php`类似这样的文件。我给目录777了 貌似也有这个问题

**Comment by lePig** [comment]
`Warning: file_put_contents(/home/host2073/domains/img.hashx.cn/public_html/data/cache/8/b3/8b31da0b38fcc7ef81d9c6b0b7104984.php) [function.file-put-contents]: failed to open stream: No such file or directory in /home/host2073/domains/img.hashx.cn/public_html/core/driver/cache/file.php on line 53`
